name: Auto Withdraw USDT

on:
  schedule:
    # Chạy mỗi ngày 07:00 giờ Việt Nam (00:00 UTC)
    - cron: '0 0 * * *'
  workflow_dispatch: {}  # cho phép trigger thủ công

jobs:
  withdraw:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Run withdraw script
        run: node withdraw.js
        env:
          PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
          PROVIDER_URL: ${{ secrets.PROVIDER_URL }}
          CONTRACT_ADDRESS: ${{ secrets.CONTRACT_ADDRESS }}
          USDT_ADDRESS: ${{ secrets.USDT_ADDRESS }}
